config_dict = {
    'cartpole_omegaconf_bs': {
            'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/braxppo_cartpoleswingup_omegaconf_biasscale',
            'env_name': 'CartpoleSwingup',
            'obs_dim': 5,
            'action_dim': 1,
            'num_envs': 2048,
            'unroll_length': 30,
            'num_minibatches': 32,
            'update_epochs': 16,
            'num_timesteps': 1e8,
            'minibatch_size': 1024,
            'base_layer_size': 4,
        },
    'ppc_omegaconf_bs': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/braxppo_pandapickcube_omegaconf_biasscale',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 4,
    },
    'ppc_megasweep': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/ppc_biasscale_megasweep',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 4,
    },
    'ant_maze': {  
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/ant_maze',
        'env_name': 'ant_u_maze',
        'obs_dim': 31,
        'action_dim': 8,
        'num_envs': 1024,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 300000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'ant_u_maze': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/ant_u_maze',
        'env_name': 'ant_u_maze',
        'obs_dim': 31,
        'action_dim': 8,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 300000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'ant_u4_maze': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/ant_u4_maze',
        'env_name': 'ant_u4_maze',
        'obs_dim': 31,
        'action_dim': 8,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 300000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'ant_hardest_maze': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/ant_hardest_maze',
        'env_name': 'ant_hardest_maze',
        'obs_dim': 31,
        'action_dim': 8,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 300000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid',
        'env_name': 'humanoid',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_u_maze': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid_u_maze',
        'env_name': 'humanoid_u_maze',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_u_maze_long': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid_u_maze',
        'env_name': 'humanoid_u_maze',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 2500000000,  
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_big_maze': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid_big_maze',
        'env_name': 'humanoid_big_maze',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'ppc': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/ppc',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 4,
    },
    'cartpole': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/cartpole',
        'env_name': 'CartpoleSwingup',
        'obs_dim': 5,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1e8,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'g1rough_updated': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/mgk/muprljax/newenvs_newnonlin/g1rough',
        'env_name': 'G1JoystickRoughTerrain',
        'obs_dim': 103,
        'action_dim': 29,
        'num_envs': 32768,
        'unroll_length': 32,
        'num_minibatches': 32,
        'update_epochs': 5,
        'num_timesteps': 4000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_orthog': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid',
        'env_name': 'humanoid',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_u_maze_orthog': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid_u_maze',
        'env_name': 'humanoid_u_maze',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_omegasweep': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid',
        'env_name': 'humanoid',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_u_maze_omegasweep': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid_u_maze',
        'env_name': 'humanoid_u_maze',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 1000000000,
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'humanoid_u_maze_lrtrans': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin/humanoid_u_maze',
        'env_name': 'humanoid_u_maze',
        'obs_dim': 271,
        'action_dim': 17,
        'num_envs': 512,
        'unroll_length': 10,
        'num_minibatches': 16,
        'update_epochs': 16,
        'num_timesteps': 2500000000,  
        'minibatch_size': 1024,
        'base_layer_size': 4,
    },
    'cartpole_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24/cartpole',
        'env_name': 'CartpoleSwingup',
        'obs_dim': 5,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1e8,
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    'panda_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24/ppc',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 1,
    },
    'cartpolesparse_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july25/cartpolesparse',
        'env_name': 'CartpoleSwingupSparse',
        'obs_dim': 5,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1e8,
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    'cheetah_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july25/halfcheetah',
        'env_name': 'CheetahRun',
        'obs_dim': 17,
        'action_dim': 6,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 200000000, 
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },

    'cheetah_10seeds_26': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july26/halfcheetah',
        'env_name': 'CheetahRun',
        'obs_dim': 17,
        'action_dim': 6,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1000000000, 
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    
    'swimmer_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july25/swimmer',
        'env_name': 'SwimmerSwimmer6',
        'obs_dim': 25,
        'action_dim': 5,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 200000000,  
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    'cartpole_omegasweep': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24_omegasweep/cartpole',
        'env_name': 'CartpoleSwingup',
        'obs_dim': 5,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1e8,
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    'ppc_omegasweep': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/mgk/muprljax/newenvs_newnonlin_july24_omegasweep/ppc_models',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 1,
    },
    'acrobot_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july25/acrobot',
        'env_name': 'AcrobotSwingup',
        'obs_dim': 6,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 200000000,  
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },

    'acrobot_10seeds_26': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july26/acrobot',
        'env_name': 'AcrobotSwingup',
        'obs_dim': 6,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1000000000,  
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },

    'acrobotsparse_10seeds': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july25/acrobotsparse',
        'env_name': 'AcrobotSwingupSparse',
        'obs_dim': 6,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 200000000, 
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },

    'acrobotsparse_10seeds_26': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july26/acrobotsparse',
        'env_name': 'AcrobotSwingupSparse',
        'obs_dim': 6,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1000000000, 
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },

    'cartpole_layernorm': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24/cartpole_norms',
        'env_name': 'CartpoleSwingup',
        'obs_dim': 5,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1e8,
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    'ppc_layernorm': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24/ppc_norms',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 1,
    },
    'cartpole_layernorm': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24/cartpole_norms',
        'env_name': 'CartpoleSwingup',
        'obs_dim': 5,
        'action_dim': 1,
        'num_envs': 2048,
        'unroll_length': 30,
        'num_minibatches': 32,
        'update_epochs': 16,
        'num_timesteps': 1e8,
        'minibatch_size': 1024,
        'base_layer_size': 1,
    },
    'ppc_layernorm': {
        'output_dir': '/n/netscratch/pehlevan_lab/Lab/adamlee/muprljax/newenvs_newnonlin_july24/ppc_norms',
        'env_name': 'PandaPickCube',
        'obs_dim': 66,
        'action_dim': 8,
        'num_envs': 2048,
        'unroll_length': 10,
        'num_minibatches': 32,
        'update_epochs': 8,
        'num_timesteps': 2e8,
        'minibatch_size': 512,
        'base_layer_size': 1,
    }
}



bs_dict = {
    'bias_scaling': {
        'use_bias': True,
        'bias_init_fn': 'normal',
        'bias_base_scale': 1.0,
    },
    'no_bias': {
        'use_bias': False,
        'bias_init_fn': 'normal',
        'bias_base_scale': 1.0,
    },
    'init_zeros': {
        'use_bias': True,
        'bias_init_fn': 'constant',
        'bias_base_scale': 0.0,
    },
    'bias_scaling_0.0001': {
        'use_bias': True,
        'bias_init_fn': 'normal',
        'bias_base_scale': 0.0001,
    },
    'bias_scaling_0': {
        'use_bias': True,
        'bias_init_fn': 'normal',
        'bias_base_scale': 0,
    },
}

parameterization_dict = {
    'NTK': {
        'ntk_scaling': True,
        'depth_scaling': False,
    },
    'μP+1/sqrt(L)': {
        'ntk_scaling': False,
        'depth_scaling': True,
    },
    'NTK+1/sqrt(L)': {
        'ntk_scaling': True,
        'depth_scaling': True,
    },
    'μP': {
        'ntk_scaling': False,
        'depth_scaling': False,
    },
}


dashes_dict = {
    'NTK': (3,1),
    'μP+1/sqrt(L)': "",
    'NTK+1/sqrt(L)': (5,5),
    'μP': (1, 1),
}